include:
- shippingservice.zip
kind: ArchiveUploadSpec
name: shippingservice-zip-LohH

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: shippingservice-fb49b71e-0223-4ad0-99da-95ddedc6ce71
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: gcpdemo-go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://shippingservice-zip-LohH
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-05-19T16:01:30Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: shippingservice
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 1000
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: gcpdemo-go
    namespace: default
  functionTimeout: 1000
  idletimeout: 120
  package:
    functionName: Handler
    packageref:
      name: shippingservice-fb49b71e-0223-4ad0-99da-95ddedc6ce71
      namespace: default
  requestsPerPod: 1
  resources: {}
