include:
- paymentservice.zip
kind: ArchiveUploadSpec
name: paymentservice-zip-7O37

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: paymentservice-acf009bf-e250-4f75-a433-7eb0a9668cbb
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: gcpdemo-nodejs
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://paymentservice-zip-7O37
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-05-30T03:49:48Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: paymentservice
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 1000
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: gcpdemo-nodejs
    namespace: default
  functionTimeout: 1000
  idletimeout: 120
  package:
    functionName: handler
    packageref:
      name: paymentservice-acf009bf-e250-4f75-a433-7eb0a9668cbb
      namespace: default
  requestsPerPod: 1
  resources: {}
