include:
- adservice.zip
kind: ArchiveUploadSpec
name: adservice-zip-JeQn

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: adservice-f05f7ccb-d33b-457e-8f4d-1d46715092ca
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: gcpdemo-java
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://adservice-zip-JeQn
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-05-22T07:01:16Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: adservice
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: gcpdemo-java
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: adservice.Adservice
    packageref:
      name: adservice-f05f7ccb-d33b-457e-8f4d-1d46715092ca
      namespace: default
  requestsPerPod: 1
  resources: {}
