include:
- adservice-1.0.0-jar-with-dependencies.jar
kind: ArchiveUploadSpec
name: adservice-1-0-0-jar-with-dependencies-jar-2zQl

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: adservice-5ba470e1-907a-49c3-ac21-0fe554c53358
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://adservice-1-0-0-jar-with-dependencies-jar-2zQl
  environment:
    name: gcpdemo-java
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2022-05-22T09:06:15Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: adservice
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: gcpdemo-java
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: adservice.Adservice
    packageref:
      name: adservice-5ba470e1-907a-49c3-ac21-0fe554c53358
      namespace: default
  requestsPerPod: 1
  resources: {}
