apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 6204aecf-fe4b-46a6-ab8d-d5c9ac630d77
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: paymentservice
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /payment
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /payment
