apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 972a6d20-5be9-4475-8bc2-7e7fd506f2de
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: cartservice
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /cart
    tls: ""
  method: ""
  methods:
  - POST
  - GET
  - DELETE
  prefix: ""
  relativeurl: /cart
