apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: d09d2f35-3cca-427f-a1cb-ec07647a3f92
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: adservice
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /ad
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /ad
