apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 6699221c-e88f-490b-ae8d-2a0d6ca2f1ee
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: adservice
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /ad
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /ad
