apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 7518d1fe-0f4c-4024-bc12-54eb876bd70d
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: emailservice
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /email
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /email
