apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: e37b5588-6042-4b18-adf2-7a41254b0f87
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: productcatalogservice
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /product
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /product
